#!/usr/bin/env python
import getpass
import sys
PY3 = (sys.version_info[0] >= 3)
if not PY3:
    input = raw_input

print("Mock SSH client for tests. Do not enter real security info.")

pw = getpass.getpass('password:')
if pw != 's3cret':
    print('Permission denied!')
    sys.exit(1)

prompt = "$"
while True:
    cmd = input(prompt)
    if cmd.startswith('PS1='):
        prompt = eval(cmd[4:]).replace('\$', '$')
    elif cmd == 'ping':
        print('pong')
    elif cmd in ('exit', 'logout'):
        break